### ISSUE TITLE
auction-live  is unavailable

### ISSUE THREAD

**Issue by man-chen-TW** [HMellor/auction-website#20]
**Describe the bug**

**To Reproduce**
1. Go to 'submit bid'
2. Click on 'submit bid'
auctions.js:146 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at auctions.js:146:26

**Additional context**

Firestore has not any auction-live  data

**Comment by man-chen-TW** [comment]
![image](https://user-images.githubusercontent.com/54659202/218075146-a1645cc6-ab9f-4fb1-9367-6d1259958b8f.png)
After linking Firebase, all starting prices disappear, please function becomes unavailable.

**Comment by dijkhuiz** [comment]
I am also experiencing this issue.

**Comment by HMellor** [comment]
I have been able to reproduce your issue by updating to the latest Firebase. `master` is on SDK `6.5.0`, whereas the code snippets when creating a new project will be on SDK `9.20.0`.

I'm working on updating this in #21

**Comment by HMellor** [comment]
@man-chen-TW, @dijkhuiz: Please try with v2.2.0 (check the updated instructions too), I have updated to the latest Firebase SDK.

**Comment by dijkhuiz** [comment]
Awesome! Thank you so much for the quick follow-up and you great work!

I pulled the latest version and followed your updated instructions. It seems that something is going wrong with the authentication part. I think it has some issues with the import. I get the following error:
`caught (in promise) TypeError: auth.signInAnonymously is not a function
    at popups.js:55:12
    at auth_impl.ts:603:14
`

This is a new error based on the update you did. I think you already had a user on the system you did the testing, so this error was not thrown. It only runs the function [`auth.signInAnonymously()`](https://github.com/HMellor/auction-website/blob/94340664849ff7cd9cdc06c0bce69c5aa2a60eac/js/popups.js#L55) when a user is not know. Do you have any idea what could cause this error? I checked and you did import auth in [the firebase.js-file](https://github.com/HMellor/auction-website/blob/94340664849ff7cd9cdc06c0bce69c5aa2a60eac/js/firebase.js#L3). You then created a constant that is exported with the name auth [in that file](https://github.com/HMellor/auction-website/blob/94340664849ff7cd9cdc06c0bce69c5aa2a60eac/js/firebase.js#L21) as well. Furthermore, in popup.js you are [importing auth from firebase.js](https://github.com/HMellor/auction-website/blob/94340664849ff7cd9cdc06c0bce69c5aa2a60eac/js/popups.js#L2).

I do not understand why it does not recognizes the function. I have a feeling it has something to do with the import and references between files. Do you have any idea?

**Comment by HMellor** [comment]
You're right, I was already signed in to an account when I made that release. I'll fix it and bump the release tag until it works (no point in a broken release)

**Comment by HMellor** [comment]
Ok try with the latest commit @dijkhuiz

**Comment by HMellor** [comment]
@dijkhuiz I've put some work in over the weekend to fully update the whole repo. I'm sure I could sit here longer and come up with more things to change/add, but for the moment I'm happy with it. 

Please check out the latest release ([Release v2.4.0](https://github.com/HMellor/auction-website/releases/tag/v2.4.0)) as I've added some cool features (such as a monitoring dashboard) that you'll probably find helpful when you run your auction.

**Comment by HMellor** [comment]
Closing as this is for an old version of the site
