### ISSUE TITLE
Firebase/Firestore setup, etc.

### ISSUE THREAD

**Issue by paulwuethrich** [hmellor/auction-website#79]
Apologies for the basic question but are there undocumented steps associated with "Creating an admin account and initializing your auctions" section (or any other sections) within the README?  Cloning and running locally while pointing to the default firebase/firestore instance specified in the default config.jsx file works without issue but no luck when trying to get it working on a separate firebase/firestore environment.

Obviously missing something simple but it's not evident just yet

**Comment by hmellor** [comment]
May I ask what you did to resolve your issue?

If there's a gap in the documentation I'd like to fix it

**Comment by paulwuethrich** [comment]
Thanks for the reply Harry - we're actually not sure but here's the sequence of our attempts.

1) Found this several weeks ago as part of looking for something simple to support a simple fundraiser for a small non-profit geared towards disabled women in wheel chairs (founder is a very close friend of ours).  Got the demo working and then branched locally in order to play around with making changes, etc. but stuck on the firebase section referred to above whereby the step referring to "Then go to your Firestore console and find the document for the user you just created." did not work as nothing was displaying within firestore.  Made several attempts but got nowhere.
2) Made another attempt but used my son as a second pair of eyes to walk through the docs using the same environment (local desktop, same google account, etc.).  Initially same issue and then it worked but we did not get a chance to identify what was different
3) Had my son run through this again but at home on his own desktop using his own accounts.  No luck as he got stuck per (1) above.  Was planning on trying to diff the environments this weekend but either way it seems like we're missing something simple.

**Comment by hmellor** [comment]
I've made some improvements to the documentation (and a couple to the website itself).

You can see these changes in the [latest release](https://github.com/hmellor/auction-website/releases/tag/v3.2.0) or by updating your local version to the latest commit on `main`.

Let me know if the newer instructions are better or if there's still anything you get stuck on.
