### ISSUE TITLE
"SyntaxError: Unexpected reserved word" error on "npm run build"

### ISSUE THREAD

**Issue by kylemd** [hmellor/auction-website#87]
**Describe the bug**
When attempting to build, vite fails to build due to an async error.

**To Reproduce**
1. Cloned to desktop
2. Run either "npm run dev" or "npm run build"

**Expected behavior**
For it to build!

**Screenshots**
![Clipboard Image](https://github.com/user-attachments/assets/df52a7ef-c20f-4e81-92f8-8dd8f34cfd8e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 
![Clipboard Image (1)](https://github.com/user-attachments/assets/ba3f305d-fece-48d7-8ad3-f49aa78c99a9)

**Comment by kylemd** [comment]
Resolved. Very clearly says I need Node 21. I was on version 12 as you can see above. Sorry!

**Comment by hmellor** [comment]
No problem!

I'd be happy to support multiple versions of Node, but I'd want some automated testing in place first otherwise it would become a nightmare for me to maintain.
